# Data Preprocessing

In this notebook, we prepare the daily energy consumption data for training the LSTM model.

Steps:
- Load cleaned dataset
- Select features
- Normalize the data
- Create sliding windows
- Split into training and testing sets

## Section 2: Import Libraries

In [40]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

## Section 3: Load Clean Dataset

In [41]:
daily_data = pd.read_csv(
    "daily_energy_data.csv",
    index_col=0,
    parse_dates=True
)

daily_data.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,
2006-12-16,3.053475,0.088187,236.243763,13.082828,0.000000,1.378788,12.439394
2006-12-17,2.354486,0.156949,240.087028,9.999028,1.411806,2.907639,9.264583
2006-12-18,1.530435,0.112356,241.231694,6.421667,0.738194,1.820139,9.734722
2006-12-19,1.157079,0.104821,241.999313,4.926389,0.582639,5.279167,4.303472
2006-12-20,1.545658,0.111804,242.308063,6.467361,0.000000,1.838889,9.765972

## Section 4: Check Dataset

In [42]:
print(daily_data.shape)

daily_data.info()

(1442, 7)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1442 entries, 2006-12-16 to 2010-11-26
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Global_active_power    1433 non-null   float64
 1   Global_reactive_power  1433 non-null   float64
 2   Voltage                1433 non-null   float64
 3   Global_intensity       1433 non-null   float64
 4   Sub_metering_1         1433 non-null   float64
 5   Sub_metering_2         1433 non-null   float64
 6   Sub_metering_3         1433 non-null   float64
dtypes: float64(7)
memory usage: 90.1 KB

## Section 5: Feature Selection

In [43]:
features = [
    'Global_active_power',
    'Global_reactive_power',
    'Voltage',
    'Global_intensity',
    'Sub_metering_1',
    'Sub_metering_2',
    'Sub_metering_3'
]

data = daily_data[features]

data.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,
2006-12-16,3.053475,0.088187,236.243763,13.082828,0.000000,1.378788,12.439394
2006-12-17,2.354486,0.156949,240.087028,9.999028,1.411806,2.907639,9.264583
2006-12-18,1.530435,0.112356,241.231694,6.421667,0.738194,1.820139,9.734722
2006-12-19,1.157079,0.104821,241.999313,4.926389,0.582639,5.279167,4.303472
2006-12-20,1.545658,0.111804,242.308063,6.467361,0.000000,1.838889,9.765972

In [44]:
daily_data = daily_data.dropna().reset_index(drop=True)

In [45]:
print(len(daily_data))

1433

In [46]:
print(daily_data.isna().sum())

Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
dtype: int64

## Section 6: Normalization

In [47]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(daily_data)

In [48]:
print(np.isnan(scaled_data).sum())

0

## Section 7: Check Scaling

In [49]:
print (scaled_data.shape)

scaled_data

(1433, 7)

array([[0.91678642, 0.13073198, 0.3153853 , ..., 0.        , 0.16396519,
        0.75444246],
       [0.6942518 , 0.42667057, 0.55049373, ..., 0.18174881, 0.34577587,
        0.56189193],
       [0.43190139, 0.23474981, 0.62051772, ..., 0.09503147, 0.21645057,
        0.59040559],
       ...,
       [0.34179083, 0.14708326, 0.54706415, ..., 0.09798165, 0.23519696,
        0.51484648],
       [0.26107518, 0.0982707 , 0.63914907, ..., 0.09619366, 0.03518044,
        0.21362086],
       [0.31977106, 0.16292032, 0.56297334, ..., 0.1100822 , 0.0362503 ,
        0.47967332]], shape=(1433, 7))

## Section 8: Sliding Window

In [50]:
window_size = 60

X = []
y = []

for i in range (window_size , len(scaled_data)) :

    X.append( scaled_data[i-window_size:i])
    
    y.append( scaled_data[i,0])

## Section 9: Convert to NumPy

In [51]:
X = np.array(X)
y = np.array(y)

## Section 10: Check Shapes

In [52]:
print(X.shape)

print (y.shape)

(1373, 60, 7)
(1373,)

## Section 11: Train/Test Split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    shuffle=False
)

## Section 12: Check Shapes

In [54]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(1098, 60, 7)
(275, 60, 7)
(1098,)
(275,)

## Section 13: Save Prepared Data

In [55]:
np.save("X_train.npy", X_train)
np.save("X_test.npy", X_test)

np.save("y_train.npy", y_train)
np.save("y_test.npy", y_test)

## Nootbook Summary

In [56]:
print("=" * 50)
print("Training Set Shape")
print(X_train.shape)
print(y_train.shape)

print()

print("Testing Set Shape")
print(X_test.shape)
print(y_test.shape)
print("=" * 50)

==================================================
Training Set Shape
(1098, 60, 7)
(1098,)

Testing Set Shape
(275, 60, 7)
(275,)
==================================================